import { trpc } from "@/lib/trpc";
import {
  Activity, AlertTriangle, ArrowUpRight, BrainCircuit, Check, CheckCircle2, ChevronRight,
  CircleDot, Clock3, Code2, Database, Eye, FileCode2, GitBranch, LockKeyhole, Play,
  Radar, RefreshCw, ShieldCheck, Sparkles, Waypoints, Wrench, XCircle,
} from "lucide-react";
import { useMemo, useState } from "react";
import { Link, useLocation } from "wouter";

const navigation = [
  { label: "Command center", href: "/", icon: Waypoints },
  { label: "Inspection findings", href: "/findings", icon: Radar },
  { label: "Repair candidates", href: "/repairs", icon: Wrench },
  { label: "Deployments", href: "/deployments", icon: GitBranch },
  { label: "Engineering memory", href: "/memory", icon: BrainCircuit },
];

const autonomyCopy = {
  observer: { title: "Observer", detail: "Inspect only · never change", level: "L0" },
  repair: { title: "Repair", detail: "Create previews · operator approval", level: "L1" },
  autonomous: { title: "Autonomous", detail: "Repair, test, promote by policy", level: "L2" },
  "self-optimizing": { title: "Self-optimizing", detail: "Governed experiments · keep or revert", level: "L3" },
} as const;

function Signal({ tone = "healthy" }: { tone?: "healthy" | "warning" | "danger" | "neutral" }) {
  const colors = { healthy: "text-emerald-400 bg-emerald-400", warning: "text-amber-300 bg-amber-300", danger: "text-rose-400 bg-rose-400", neutral: "text-sky-300 bg-sky-300" };
  return <span className={`status-dot inline-block h-1.5 w-1.5 rounded-full ${colors[tone]}`} aria-hidden="true" />;
}

function ToneBadge({ children, tone = "neutral" }: { children: React.ReactNode; tone?: "healthy" | "success" | "warning" | "danger" | "neutral" }) {
  const styles = { healthy: "border-emerald-400/20 bg-emerald-400/10 text-emerald-300", success: "border-emerald-400/20 bg-emerald-400/10 text-emerald-300", warning: "border-amber-300/20 bg-amber-300/10 text-amber-200", danger: "border-rose-400/20 bg-rose-400/10 text-rose-300", neutral: "border-sky-300/15 bg-sky-300/8 text-sky-200" };
  return <span className={`inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 font-mono text-[10px] uppercase tracking-[0.14em] ${styles[tone]}`}>{children}</span>;
}

export default function Home() {
  const [, navigate] = useLocation();
  const [location] = useLocation();
  const [analysis, setAnalysis] = useState<unknown>(null);
  const [analysisOpen, setAnalysisOpen] = useState(false);
  const snapshotQuery = trpc.controlPlane.snapshot.useQuery(undefined, { refetchInterval: 20_000 });
  const discoveryQuery = trpc.controlPlane.discoverApplication.useQuery(undefined, { enabled: false });
  const utils = trpc.useUtils();
  const runInspection = trpc.controlPlane.runInspection.useMutation({ onSuccess: () => utils.controlPlane.snapshot.invalidate() });
  const setAutonomy = trpc.controlPlane.setAutonomy.useMutation({ onSuccess: () => utils.controlPlane.snapshot.invalidate() });
  const reviewCandidate = trpc.controlPlane.reviewCandidate.useMutation({ onSuccess: () => utils.controlPlane.snapshot.invalidate() });
  const requestPromotion = trpc.controlPlane.requestPromotion.useMutation({ onSuccess: () => utils.controlPlane.snapshot.invalidate() });
  const diagnoseFinding = trpc.controlPlane.diagnoseFinding.useMutation({ onSuccess: data => { setAnalysis(data); setAnalysisOpen(true); } });

  const snapshot = snapshotQuery.data;
  const activeNav = useMemo(() => navigation.find(item => item.href === location)?.label ?? "Command center", [location]);
  if (!snapshot) return <DashboardSkeleton />;

  const candidate = snapshot.candidates[0];
  const activeAutonomy = autonomyCopy[snapshot.autonomyLevel];
  const healthCount = snapshot.inspectors.filter(inspector => inspector.status === "healthy").length;

  return (
    <div className="control-grid min-h-screen bg-[#0b1016] text-slate-100">
      <div className="mx-auto grid min-h-screen max-w-[1720px] grid-cols-1 xl:grid-cols-[242px_minmax(0,1fr)]">
        <aside className="border-b border-white/7 bg-[#0e151d]/90 px-5 py-5 xl:border-b-0 xl:border-r xl:px-4">
          <div className="flex items-center justify-between xl:block">
            <Link href="/" className="group flex items-center gap-3">
              <div className="grid h-9 w-9 place-items-center rounded-xl border border-emerald-300/20 bg-emerald-300/10 text-emerald-300 shadow-[0_0_30px_rgb(52_211_153/0.12)]"><ShieldCheck className="h-[18px] w-[18px]" /></div>
              <div><p className="font-serif text-[16px] tracking-tight text-white">Atlas</p><p className="font-mono text-[9px] uppercase tracking-[0.19em] text-slate-500">Control plane</p></div>
            </Link>
            <div className="mt-0 flex items-center gap-2 xl:mt-9"><Signal /><span className="font-mono text-[10px] uppercase tracking-[0.14em] text-emerald-300">System guarded</span></div>
          </div>
          <div className="mt-6 hidden xl:block"><p className="px-3 font-mono text-[9px] uppercase tracking-[0.18em] text-slate-600">Governance</p><nav className="mt-3 space-y-1">{navigation.map(item => { const Icon = item.icon; const selected = activeNav === item.label; return <button key={item.href} onClick={() => navigate(item.href)} className={`flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-left text-[13px] transition-colors ${selected ? "bg-white/8 text-white" : "text-slate-400 hover:bg-white/[0.045] hover:text-slate-200"}`}><Icon className={`h-4 w-4 ${selected ? "text-emerald-300" : "text-slate-500"}`} />{item.label}{selected && <ChevronRight className="ml-auto h-3.5 w-3.5 text-emerald-300" />}</button>; })}</nav></div>
          <div className="mt-6 hidden rounded-xl border border-white/8 bg-white/[0.025] p-3 xl:block"><div className="flex items-start justify-between"><div><p className="font-mono text-[9px] uppercase tracking-[0.17em] text-slate-500">Nightly posture</p><p className="mt-1 text-sm font-medium text-slate-200">02:00 UTC scan</p></div><Clock3 className="h-4 w-4 text-slate-500" /></div><p className="mt-2 text-[11px] leading-4 text-slate-500">Inspect, prioritize, and govern candidates. No direct production writes.</p></div>
          <div className="mt-8 hidden border-t border-white/7 pt-5 xl:block"><p className="font-mono text-[9px] uppercase tracking-[0.18em] text-slate-600">Protected boundaries</p><div className="mt-3 flex flex-wrap gap-1.5"><ToneBadge><LockKeyhole className="h-3 w-3" />Auth</ToneBadge><ToneBadge>DB read-only</ToneBadge><ToneBadge>main locked</ToneBadge></div></div>
        </aside>

        <main className="min-w-0 px-4 py-5 sm:px-7 lg:px-9">
          <header className="flex flex-col gap-5 border-b border-white/8 pb-5 lg:flex-row lg:items-center lg:justify-between">
            <div><div className="flex items-center gap-2"><span className="font-mono text-[10px] uppercase tracking-[0.2em] text-emerald-300">{activeNav}</span><span className="h-1 w-1 rounded-full bg-slate-600" /><span className="font-mono text-[10px] uppercase tracking-[0.16em] text-slate-500">Vercel / {snapshot.application.productionBranch}</span></div><h1 className="mt-2 font-serif text-2xl tracking-[-0.035em] text-white sm:text-[29px]">Autonomous control plane</h1></div>
            <div className="flex flex-wrap items-center gap-2"><ToneBadge tone="healthy"><Check className="h-3 w-3" />Preview-first policy</ToneBadge><button onClick={() => discoveryQuery.refetch()} disabled={discoveryQuery.isFetching} className="inline-flex items-center gap-2 rounded-lg border border-white/10 px-3 py-2 text-xs font-semibold text-slate-300 transition-colors hover:bg-white/5 disabled:opacity-60"><Activity className={`h-3.5 w-3.5 ${discoveryQuery.isFetching ? "animate-pulse" : ""}`} />Discover app</button><button onClick={() => runInspection.mutate()} disabled={runInspection.isPending} className="inline-flex items-center gap-2 rounded-lg bg-emerald-300 px-3.5 py-2 text-xs font-semibold text-emerald-950 transition-transform hover:bg-emerald-200 active:scale-[0.97] disabled:opacity-60"><RefreshCw className={`h-3.5 w-3.5 ${runInspection.isPending ? "animate-spin" : ""}`} />Run inspection</button></div>
          </header>

          <section className="grid gap-4 py-6 2xl:grid-cols-[minmax(0,1.35fr)_minmax(360px,.65fr)]">
            <div className="soft-panel relative overflow-hidden rounded-2xl p-5 sm:p-6"><div className="absolute -right-20 -top-24 h-60 w-60 rounded-full bg-emerald-400/[0.07] blur-3xl" /><div className="relative flex flex-col justify-between gap-7"><div><div className="flex flex-wrap items-center gap-2"><ToneBadge tone="healthy"><Signal />Production guarded</ToneBadge><span className="font-mono text-[10px] text-slate-500">SOURCE OF TRUTH · MAIN</span></div><h2 className="mt-5 max-w-xl font-serif text-[25px] leading-[1.28] tracking-[-0.035em] text-slate-100 sm:text-[31px]">Repair with evidence. Promote with restraint.</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-400">Atlas observes the application against its constitution, isolates the smallest safe repair in a durable branch, and refuses promotion until re-inspection and independent review agree.</p></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><Metric label="Inspectors" value={`${healthCount}/${snapshot.inspectors.length}`} detail="healthy" icon={Radar} /><Metric label="Open findings" value={String(snapshot.findings.filter(finding => finding.state === "open" || finding.state === "candidate").length).padStart(2, "0")} detail="correlated" icon={AlertTriangle} warn /><Metric label="Candidate gates" value="5/6" detail="passed" icon={CheckCircle2} /><Metric label="Deployment" value="main" detail="locked" icon={GitBranch} /></div></div></div>
            <div className="soft-panel rounded-2xl p-5"><div className="flex items-start justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-slate-500">Active autonomy</p><h3 className="mt-2 text-xl font-semibold tracking-tight text-white">{activeAutonomy.title}</h3><p className="mt-1 max-w-[240px] text-xs leading-5 text-slate-500">{activeAutonomy.detail}</p></div><span className="rounded-lg border border-sky-300/15 bg-sky-300/10 px-2 py-1 font-mono text-xs text-sky-200">{activeAutonomy.level}</span></div><div className="mt-5 grid grid-cols-2 gap-1 rounded-xl border border-white/8 bg-black/15 p-1">{(Object.keys(autonomyCopy) as Array<keyof typeof autonomyCopy>).map(level => <button key={level} onClick={() => setAutonomy.mutate(level)} className={`rounded-lg px-2 py-2 text-left transition-colors ${snapshot.autonomyLevel === level ? "bg-white/10 text-white" : "text-slate-500 hover:text-slate-300"}`}><span className="block font-mono text-[9px] uppercase tracking-[0.13em]">{autonomyCopy[level].level}</span><span className="mt-0.5 block text-[11px] font-medium">{autonomyCopy[level].title}</span></button>)}</div>{discoveryQuery.data && <div className="mt-4 rounded-lg border border-sky-300/10 bg-sky-300/[0.045] px-3 py-2"><p className="font-mono text-[9px] uppercase tracking-[0.12em] text-sky-200">Application map refreshed</p><p className="mt-1 text-[11px] text-slate-400">{discoveryQuery.data.routes.length} routes · {discoveryQuery.data.components.length} components · {discoveryQuery.data.apiModules.length} API modules</p></div>}<div className="mt-5 flex items-center justify-between border-t border-white/7 pt-4"><div className="flex items-center gap-2"><Clock3 className="h-3.5 w-3.5 text-emerald-300" /><span className="font-mono text-[10px] uppercase tracking-[0.13em] text-slate-400">Next scan {snapshot.schedule.nextRun}</span></div><button onClick={() => navigate("/settings")} className="text-xs font-medium text-emerald-300 hover:text-emerald-200">Configure</button></div></div>
          </section>

          <section className="grid gap-4 xl:grid-cols-[minmax(0,1.04fr)_minmax(0,.96fr)]">
            <div className="soft-panel rounded-2xl"><PanelHeader eyebrow="Correlated evidence" title="Inspection findings" action="View all" onAction={() => navigate("/findings")} /><div className="divide-y divide-white/7">{snapshot.findings.map(finding => <div key={finding.id} className="group px-5 py-4 sm:px-6"><div className="flex gap-4"><div className={`mt-1 h-8 w-1 rounded-full ${finding.severity === "high" ? "bg-amber-300" : "bg-sky-300"}`} /><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><ToneBadge tone={finding.severity === "high" ? "warning" : "neutral"}>{finding.severity}</ToneBadge><span className="font-mono text-[10px] text-slate-600">{finding.affectedPath}</span></div><h3 className="mt-2 text-[15px] font-semibold text-slate-100">{finding.title}</h3><p className="mt-1 text-xs leading-5 text-slate-500">{finding.evidence.map(item => item.summary).join(" · ")}</p><div className="mt-3 flex items-center justify-between"><span className="font-mono text-[10px] uppercase tracking-[0.12em] text-slate-600">confidence {Math.round(finding.confidence * 100)}%</span><button onClick={() => diagnoseFinding.mutate({ findingId: finding.id })} className="inline-flex items-center gap-1.5 text-xs font-medium text-sky-200 hover:text-sky-100"><BrainCircuit className="h-3.5 w-3.5" />Founder analysis<ArrowUpRight className="h-3 w-3" /></button></div></div></div></div>)}</div>
            </div>
            <div className="soft-panel rounded-2xl"><PanelHeader eyebrow="Branch-isolated change" title="Repair candidate" action="Open candidate" onAction={() => navigate("/repairs")} />{candidate ? <div className="px-5 pb-5 sm:px-6 sm:pb-6"><div className="rounded-xl border border-white/8 bg-black/15 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-mono text-[10px] uppercase tracking-[0.13em] text-emerald-300">{candidate.branch}</p><h3 className="mt-1 text-base font-semibold text-white">{candidate.title}</h3></div><ToneBadge tone="warning">Review pending</ToneBadge></div><p className="mt-3 text-xs leading-5 text-slate-500">{candidate.summary}</p><div className="mt-4 grid grid-cols-3 gap-1.5">{Object.entries(candidate.gates).map(([gate, status]) => <div key={gate} className={`rounded-md border px-2 py-2 ${status === "passed" ? "border-emerald-300/12 bg-emerald-300/[0.055]" : "border-amber-300/13 bg-amber-300/[0.055]"}`}><span className="block truncate font-mono text-[8px] uppercase tracking-[0.1em] text-slate-500">{gate.replace("-", " ")}</span><span className={`mt-1 block text-[10px] font-medium ${status === "passed" ? "text-emerald-300" : "text-amber-200"}`}>{status}</span></div>)}</div></div><div className="mt-4 flex flex-wrap gap-2"><button onClick={() => reviewCandidate.mutate({ candidateId: candidate.id, decision: "approved" })} className="inline-flex items-center gap-1.5 rounded-lg border border-emerald-300/20 bg-emerald-300/10 px-3 py-2 text-xs font-semibold text-emerald-200 hover:bg-emerald-300/15"><Check className="h-3.5 w-3.5" />Approve review</button><button onClick={() => reviewCandidate.mutate({ candidateId: candidate.id, decision: "rejected" })} className="inline-flex items-center gap-1.5 rounded-lg border border-white/10 px-3 py-2 text-xs font-semibold text-slate-300 hover:bg-white/5"><XCircle className="h-3.5 w-3.5" />Reject</button><button onClick={() => requestPromotion.mutate({ candidateId: candidate.id })} className="ml-auto inline-flex items-center gap-1.5 rounded-lg px-2 py-2 text-xs font-semibold text-slate-500 hover:text-slate-300"><ArrowUpRight className="h-3.5 w-3.5" />Promotion check</button></div></div> : <EmptyPanel />}</div>
          </section>

          <section className="mt-4 grid gap-4 2xl:grid-cols-[1.08fr_.92fr]">
            <div className="soft-panel rounded-2xl p-5 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-slate-500">Preview-first delivery</p><h2 className="mt-1 text-lg font-semibold tracking-tight text-white">Production is a consequence, not a shortcut.</h2></div><ToneBadge><LockKeyhole className="h-3 w-3" />Direct writes blocked</ToneBadge></div><div className="mt-6 grid items-center gap-3 md:grid-cols-[1fr_auto_1fr_auto_1fr]"><FlowNode icon={GitBranch} label="main" sub="Production source" tone="neutral" /><FlowArrow /><FlowNode icon={Code2} label="heal/*" sub="Isolated candidate" tone="warning" /><FlowArrow /><FlowNode icon={Eye} label="Preview" sub="Re-inspect + review" tone="healthy" /></div><div className="mt-4 flex flex-wrap items-center gap-x-5 gap-y-2 border-t border-white/7 pt-4 font-mono text-[10px] uppercase tracking-[0.12em] text-slate-500"><span className="flex items-center gap-2"><CheckCircle2 className="h-3.5 w-3.5 text-emerald-300" />Build · unit · E2E · visual</span><span className="flex items-center gap-2"><ShieldCheck className="h-3.5 w-3.5 text-emerald-300" />Independent reviewer</span><span className="flex items-center gap-2"><Database className="h-3.5 w-3.5 text-sky-300" />Production DB read-only</span></div></div>
            <div className="soft-panel rounded-2xl"><PanelHeader eyebrow="Self-documenting system" title="Engineering memory" action="Browse" onAction={() => navigate("/memory")} /><div className="divide-y divide-white/7">{snapshot.memory.map((record, index) => <div key={`${record.kind}-${index}`} className="flex gap-3 px-5 py-3.5 sm:px-6"><div className={`mt-0.5 grid h-7 w-7 shrink-0 place-items-center rounded-lg ${record.protected ? "bg-sky-300/10 text-sky-200" : "bg-white/6 text-slate-400"}`}>{record.kind === "decision" ? <LockKeyhole className="h-3.5 w-3.5" /> : record.kind === "fix" ? <Wrench className="h-3.5 w-3.5" /> : record.kind === "incident" ? <AlertTriangle className="h-3.5 w-3.5" /> : <FileCode2 className="h-3.5 w-3.5" />}</div><div className="min-w-0"><div className="flex items-center gap-2"><p className="text-xs font-semibold text-slate-200">{record.title}</p>{record.protected && <span className="font-mono text-[9px] uppercase tracking-[0.1em] text-sky-200">protected</span>}</div><p className="mt-1 text-[11px] leading-4 text-slate-500">{record.summary}</p></div></div>)}</div></div>
          </section>

          <section className="mt-4 pb-8"><div className="soft-panel rounded-2xl"><PanelHeader eyebrow="Durable audit trail" title="Governance activity" action="Audit ledger" onAction={() => navigate("/deployments")} /><div className="divide-y divide-white/7">{snapshot.auditEvents.slice(0, 4).map(event => <div key={event.id} className="flex items-center gap-4 px-5 py-3.5 sm:px-6"><div className="hidden h-8 w-8 shrink-0 place-items-center rounded-lg border border-white/8 bg-white/[0.035] sm:grid">{event.type === "inspection" ? <Radar className="h-3.5 w-3.5 text-emerald-300" /> : event.type === "review" ? <ShieldCheck className="h-3.5 w-3.5 text-amber-200" /> : <GitBranch className="h-3.5 w-3.5 text-sky-200" />}</div><div className="min-w-0 flex-1"><p className="text-xs font-semibold text-slate-200">{event.title}</p><p className="mt-0.5 truncate text-[11px] text-slate-500">{event.detail}</p></div><ToneBadge tone={event.tone}>{event.type}</ToneBadge></div>)}</div></div></section>
        </main>
      </div>
      {analysisOpen && <AnalysisModal analysis={analysis} onClose={() => setAnalysisOpen(false)} />}
    </div>
  );
}

function Metric({ label, value, detail, icon: Icon, warn = false }: { label: string; value: string; detail: string; icon: typeof Radar; warn?: boolean }) { return <div className="rounded-xl border border-white/8 bg-black/15 p-3"><div className="flex items-center justify-between"><span className="font-mono text-[9px] uppercase tracking-[0.13em] text-slate-500">{label}</span><Icon className={`h-3.5 w-3.5 ${warn ? "text-amber-200" : "text-slate-500"}`} /></div><div className="mt-3 flex items-end justify-between"><span className="text-xl font-semibold tracking-tight text-slate-100">{value}</span><span className={`font-mono text-[9px] uppercase ${warn ? "text-amber-200" : "text-emerald-300"}`}>{detail}</span></div></div>; }
function PanelHeader({ eyebrow, title, action, onAction }: { eyebrow: string; title: string; action: string; onAction: () => void }) { return <div className="flex items-end justify-between gap-3 px-5 pb-4 pt-5 sm:px-6"><div><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-slate-500">{eyebrow}</p><h2 className="mt-1 text-lg font-semibold tracking-tight text-white">{title}</h2></div><button onClick={onAction} className="text-xs font-medium text-slate-400 transition-colors hover:text-emerald-200">{action}</button></div>; }
function FlowNode({ icon: Icon, label, sub, tone }: { icon: typeof GitBranch; label: string; sub: string; tone: "neutral" | "warning" | "healthy" }) { const colors = { neutral: "border-sky-300/15 bg-sky-300/[0.05] text-sky-200", warning: "border-amber-300/15 bg-amber-300/[0.05] text-amber-200", healthy: "border-emerald-300/15 bg-emerald-300/[0.05] text-emerald-200" }; return <div className={`rounded-xl border p-3 ${colors[tone]}`}><div className="flex items-center gap-2"><Icon className="h-3.5 w-3.5" /><span className="text-sm font-semibold">{label}</span></div><p className="mt-1.5 font-mono text-[9px] uppercase tracking-[0.1em] opacity-65">{sub}</p></div>; }
function FlowArrow() { return <div className="hidden md:grid place-items-center"><ArrowUpRight className="h-4 w-4 rotate-45 text-slate-600" /></div>; }
function EmptyPanel() { return <div className="px-6 py-10 text-center text-sm text-slate-500">No repair candidate is active.</div>; }
function DashboardSkeleton() { return <div className="control-grid min-h-screen bg-[#0b1016] p-6"><div className="mx-auto w-full max-w-[1380px] animate-pulse space-y-4"><div className="h-14 rounded-xl bg-white/5" /><div className="grid gap-4 lg:grid-cols-3"><div className="h-64 rounded-2xl bg-white/5 lg:col-span-2" /><div className="h-64 rounded-2xl bg-white/5" /></div><div className="h-80 rounded-2xl bg-white/5" /></div></div>; }
function AnalysisModal({ analysis, onClose }: { analysis: unknown; onClose: () => void }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-black/65 p-4 backdrop-blur-sm"><div className="soft-panel w-full max-w-2xl rounded-2xl p-5 sm:p-6"><div className="flex items-start justify-between gap-4"><div><ToneBadge tone="neutral"><Sparkles className="h-3 w-3" />Founder Layer</ToneBadge><h2 className="mt-3 text-xl font-semibold text-white">Independent diagnosis brief</h2></div><button onClick={onClose} className="rounded-lg p-2 text-slate-400 hover:bg-white/5 hover:text-white"><XCircle className="h-5 w-5" /></button></div><pre className="mt-5 max-h-[58vh] overflow-auto rounded-xl border border-white/8 bg-black/20 p-4 font-mono text-[11px] leading-5 text-slate-300">{JSON.stringify(analysis, null, 2)}</pre><p className="mt-4 text-xs leading-5 text-slate-500">This analysis is advisory. A branch-isolated repair still requires the full policy gates and an independent Reviewer decision before production promotion.</p></div></div>; }
