import { invokeLLM } from "../_core/llm";
import type { CorrelatedFinding } from "../../autonomous/inspection/contracts";
import type { EngineeringMemory } from "../../autonomous/memory/contracts";

export type FounderLayerAnalysis = { architect: { intent: string; invariants: string[]; protectedBoundaries: string[] }; inspector: { diagnosis: string; confidence: number; evidenceGaps: string[] }; engineer: { minimalPatch: string; targetedTests: string[]; risk: "low" | "medium" | "high" }; reviewer: { verdict: "approve" | "reject" | "needs-evidence"; rationale: string; regressionsToCheck: string[] } };

const outputSchema = { type: "json_schema" as const, json_schema: { name: "founder_layer_analysis", strict: true, schema: { type: "object", properties: { architect: { type: "object", properties: { intent: { type: "string" }, invariants: { type: "array", items: { type: "string" } }, protectedBoundaries: { type: "array", items: { type: "string" } } }, required: ["intent", "invariants", "protectedBoundaries"], additionalProperties: false }, inspector: { type: "object", properties: { diagnosis: { type: "string" }, confidence: { type: "number" }, evidenceGaps: { type: "array", items: { type: "string" } } }, required: ["diagnosis", "confidence", "evidenceGaps"], additionalProperties: false }, engineer: { type: "object", properties: { minimalPatch: { type: "string" }, targetedTests: { type: "array", items: { type: "string" } }, risk: { type: "string", enum: ["low", "medium", "high"] } }, required: ["minimalPatch", "targetedTests", "risk"], additionalProperties: false }, reviewer: { type: "object", properties: { verdict: { type: "string", enum: ["approve", "reject", "needs-evidence"] }, rationale: { type: "string" }, regressionsToCheck: { type: "array", items: { type: "string" } } }, required: ["verdict", "rationale", "regressionsToCheck"], additionalProperties: false } }, required: ["architect", "inspector", "engineer", "reviewer"], additionalProperties: false } } };

export async function analyzeFindingWithFounderLayer(finding: CorrelatedFinding, relevantMemory: EngineeringMemory[] = []): Promise<FounderLayerAnalysis> {
  const response = await invokeLLM({ model: "gpt-5-mini", messages: [{ role: "system", content: "You are a safety-first autonomous web engineering council. Treat main as production, never recommend direct production modification, preserve protected boundaries, and require preview-first Vercel validation. Reuse engineering memory only when it fits the current evidence, and explain residual risk through the Reviewer. Return structured JSON only." }, { role: "user", content: JSON.stringify({ finding, relevantMemory, constitution: { repairBranchPrefix: "heal/", requiredGates: ["build", "unit", "e2e", "visual", "preview-browser", "independent-review"], protectedBoundaries: ["authentication", "production-database", "deployment-policy"] } }) }], response_format: outputSchema });
  const content = response.choices[0]?.message?.content;
  if (typeof content !== "string") throw new Error("Founder Layer returned no textual structured analysis.");
  return JSON.parse(content) as FounderLayerAnalysis;
}
